---
title: "Lab 9 - Generative Art"
author: "Alisa Krasilnikov"
format: html
embed-resources: true
editor: source
---

```{r, message=FALSE, echo=TRUE}
#| label: libraries 

library(ggplot2)
library(dplyr)
library(rayshader)
library(tibble)
library(ambient)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(tictoc)
library(dplyr)
```

```{r, warning = FALSE}
iris |> 
  ggplot() + 
  geom_violin(aes(Petal.Width, Petal.Length, colour = Species), size = 25, show.legend = FALSE) +
  geom_violin(aes(Sepal.Width, Sepal.Length, colour = Species), size = 25, show.legend = FALSE) +
  geom_smooth(aes(Petal.Width, Petal.Length, colour = Species), method = "loess", size = 2, se = FALSE, show.legend = FALSE, color = "orange") + 
  geom_jitter(aes(Petal.Width, Petal.Length, colour = Species), size = 2, color = "#FDB915") +
  coord_polar() +
  theme_void() + 
  scale_color_manual(values = c(
    setosa = "#5A4FCF",
    versicolor = "#ce70e8",
    virginica = "#a347e5"
  )) 
```

```{r}
#Setting colors
sample_canva2 <- function(seed = NULL, n = 4) {
  
  if(!is.null(seed)) set.seed(seed)
  sample(ggthemes::canva_palettes, 1)[[1]] |>
    (\(x) colorRampPalette(x)(n))()  
}
```

```{r}
#Function that produces coordinates that get put into other noise processes
transform_to_curl_space <- function(x, y, frequency = 1, octaves = 10) {
  curl_noise(
    generator = fracture,
    noise = gen_simplex,
    fractal = fbm,
    octaves = octaves,
    frequency = frequency,
    x = x,
    y = y
  )
}
```

```{r}
#Create cells
define_worley_cells <- function(x, y, frequency = 3, octaves = 6) {
  fracture(
    noise = gen_worley,
    fractal = billow,
    octaves = octaves,
    frequency = frequency,
    value = "cell",
    x = x,
    y = y
  ) |>
    rank() |> 
    normalise()
}
```

```{r}
#Create noise
simplex_noise <- function(x, y, frequency = .1, octaves = 10) {
  fracture(
    noise = gen_simplex,
    fractal = ridged,
    octaves = octaves,
    frequency = frequency,
    x = x,
    y = y
  ) |>
    normalise()
}
```
```{r}
ice_floe <- function(seed) {
  
  set.seed(seed)
  
  grid <- long_grid(
    x = seq(0, 1, length.out = 2000),
    y = seq(0, 1, length.out = 2000)
  )
  
  coords <- transform_to_curl_space(grid$x, grid$y)
  
  grid |>
    mutate(
      cells = define_worley_cells(coords$x, coords$y, frequency = 8, octaves = 17), #Set frequency to 8, octaves to 17
      paint = simplex_noise(x + cells, y + cells, frequency = 0.2), #Set frequency to 0.2
      paint = normalise(paint)
    ) |>
    as.array(value = paint)
}
```

```{r}
shaded_ice_floe <- function(seed) {
  
  art <- ice_floe(seed)
  
  height_shade(
    heightmap = art,
    texture = sample_canva2(seed = 600, n = 800) #Made it pink
  ) |>
    add_shadow(
      shadowmap = ray_shade(
        heightmap = art, 
        sunaltitude = 40, #Make the sun a little further
        sunangle = 70,
        multicore = TRUE, 
        zscale = .005
      ), 
      max_darken = .3 #I want it pretty light
    ) |>
    plot_map()
}

shaded_ice_floe(11032003)
```

